### ISSUE TITLE
[BUG] master is still broken, broken GPG

### ISSUE THREAD

**Issue by hamin** [swiftlang/swift-docker#10]
Running latest master is still broken @swizzlr 

```
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
```

**Comment by swizzlr** [comment]
Well that's just crap.

**Comment by swizzlr** [comment]
`RUN gpg --verify swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04.tar.gz`
should read
`RUN gpg --verify swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04.tar.gz.sig`

If you could patch that that would be great, I'm working on this REPL thing right now.

**Comment by hamin** [comment]
@swizzlr on it

**Comment by swizzlr** [comment]
@hamin nvm, just fixed it

**Comment by swizzlr** [comment]
https://github.com/swiftdocker/docker-swift/commit/d025eb3bc9456e77346842815a03380384be0238

**Comment by hamin** [comment]
awesome

**Comment by swizzlr** [comment]
I've gotta turn in for the night, so when that build goes out let's tag it 0.0.1, "release" it and carry on tomorrow.
