### ISSUE TITLE
Can't pull repositories from github via HTTPS

### ISSUE THREAD

**Issue by andradei** [swiftlang/swift-docker#102]
I'm trying to compile my project on the swift:4.0.2 image and get the following errors:

Notice the git version at the end is 2.7.4, the newest one as of now is 2.15.x, I don't know if that's the issue.

```
# swift build -c release --static-swift-stdlib
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/vapor/leaf-provider.git
Fetching https://github.com/vapor/core.git
Fetching https://github.com/vapor/debugging.git
Fetching https://github.com/vapor/leaf.git
Fetching https://github.com/vapor/random.git
Fetching https://github.com/vapor/sockets.git
Fetching https://github.com/vapor/bcrypt.git
Fetching https://github.com/vapor/bits.git
Fetching https://github.com/vapor/console.git
Fetching https://github.com/vapor/node.git
Fetching https://github.com/vapor/tls.git
error: failed to clone; Cloning into bare repository '/Source/.build/repositories/vapor.git--3231922947425880948'...
fatal: unable to access 'https://github.com/vapor/vapor.git/': Could not resolve host: github.com
error: product dependency 'Vapor' not found
error: product dependency 'LeafProvider' not found
error: product dependency 'Testing' not found
# git --version
git version 2.7.4
```

## Package.swift

```swift
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "my_project",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.2.0")),
        .package(url: "https://github.com/vapor/leaf-provider.git", .upToNextMajor(from: "1.1.0")),
    ],
    targets: [
        .target(name: "App", dependencies: ["Vapor", "LeafProvider"],
               exclude: [
                   "Config",
                   "Database",
                   "Public",
                   "Resources"
               ]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)
```

**Comment by swizzlr** [comment]
Could you update with your Package.swift?

**Comment by florianreinhart** [comment]
This sounds like a connection or DNS issue: `Could not resolve host: github.com`.

Can you run `curl "https://github.com"` inside the container?

**Comment by andradei** [comment]
@swizzlr I updated the OP with Package.swift. Thank you for helping.

@florianreinhart `curl` fails for github, google, etc., so it is a container issue. This problem, however, arises only on my AWS EC2 Ubuntu 16.04 instance. I can run `curl` successfully on my local machine (macOS). So would this be related to Ubuntu (or a different version of Docker)?

**Comment by swizzlr** [comment]
@andradei Have you checked your EC2 firewall rules? Can you curl from outside Docker on that machine? What networks have you attached to the container in Docker?

This works on my and many other machines, so I think it's something to do with how you're running the container, not the image itself.

**Comment by andradei** [comment]
@swizzlr Firewall is letting 443 traffic in/out. I can `curl` from outside of Docker on that instance. No networks attached, unless docker does it automatically.

I run the container with `docker run -ti swift:4.0.2 /bin/sh` and try to `swift build -c release --static-swift-stdlib` inside it.

**Comment by swizzlr** [comment]
This works on my Mac, Docker 17.09
```
docker run -ti swift:4.0.2 /bin/sh
...
curl https://github.com
```

Can you verify the same for yourself?

**Comment by andradei** [comment]
I upgraded my AWS docker engine to latest stable (17.09.0-ce). It works now. Now I'm having another problem in the compilation step, which is an issue for another repo.

Thanks for helping me narrow it down. I really appreciate it.
