### ISSUE TITLE
latest

### ISSUE THREAD

**Issue by crspybits** [swiftlang/swift-docker#105]
It seems that `swiftdocker/swift:latest` is still pointing to 4.0.2. I expected it to be pointing to 4.0.3.

Thanks!

**Comment by swizzlr** [comment]
Whoops, looks like we didn't add back the latest tag in the automatic build.

I've added it now and triggered another.

In the meantime, FROM swift:latest should point to 4.0.3.

Let me know if the build works and we can close it.

**Comment by crspybits** [comment]
Just tried this, and get:

Step 1/5 : FROM swiftdocker/swift:4.0.3
manifest for swiftdocker/swift:4.0.3 not found

If I use `FROM swiftdocker/swift:latest`, my docker build doesn't seem to pull down anything new...

I get:

MacBook-Pro:Building chris$ docker build -t swift-ubuntu:latest .
Sending build context to Docker daemon  15.87kB
Step 1/5 : FROM swiftdocker/swift:latest
 ---> 45b245d4bc04
Step 2/5 : LABEL maintainer "Chris Prince <chris@SpasticMuffin.biz>"
 ---> Using cache
 ---> 66c220d0ca36
Step 3/5 : LABEL Description "Docker image for building the Swift SyncServer server"
 ---> Using cache
 ---> 80000fa36415
Step 4/5 : RUN apt-get -q update && 	apt-get -q install -y 		uuid-dev     	libmysqlclient-dev     	jq     && rm -r /var/lib/apt/lists/*
 ---> Using cache
 ---> 8c644a961b10
Step 5/5 : RUN swift --version
 ---> Using cache
 ---> 63657eb6e4de
Successfully built 63657eb6e4de
Successfully tagged swift-ubuntu:latest

**Comment by swizzlr** [comment]
You'll need to smash the cache by running `docker build --no-cache`. Looks like we need to tag this.

However, in this case I would strongly recommend you use the official distribution: `FROM swift:4.0.3`
