### ISSUE TITLE
Any chance of getting Dev snapshots?

### ISSUE THREAD

**Issue by masters3d** [swiftlang/swift-docker#106]
Any plans to include development snapshots like `Swift 4.1 Development` ? 

This would be very helpful in running tests against future versions.

**Comment by masters3d** [comment]
For reference: https://hub.docker.com/r/norionomura/swift/

**Comment by swizzlr** [comment]
We would hugely welcome contributed dev snapshots! Just open a PR!

**Comment by masters3d** [comment]
What do you think @norio-nomura ? I use your snapshots at
https://github.com/norio-nomura/docker-swift which I love for TravisCI.  No sure if you would be interested in contributing here but I just wanted to ask since you are already doing all the work.

**Comment by Sharom** [comment]
It would be very useful to have tag `dev` with night build of development release.
It's very convenient for continuous integration of packages, especially for libraries.

**Comment by masters3d** [comment]
Can it be automated? Or perhaps the swift project can vend them as part of their build process. Does anybody know of that part is open source?

**Comment by swizzlr** [comment]
@masters3d we would love for it to be a part of the Swift CI.

**Comment by masters3d** [comment]
Closing in favor of https://github.com/swiftdocker/docker-swift/issues/55
