### ISSUE TITLE
Support for ARM64v8

### ISSUE THREAD

**Issue by lag-linaro** [swiftlang/swift-docker#116]
Now that Docker's Official Images support multiple architectures would you guys be interested to enable this project for ARM64v8?

**Comment by odidev** [comment]
Is there anything going in this direction?

I am trying to compile Swift on arm64, but I am getting a lot of errors.
I managed to resolve most of them, but still, it would be great to get some assistance.

In addition, it takes a hell lot of time to compile Swift and then face errors, making me do it in cycles.

**Comment by odidev** [comment]
Finally, I have managed to compile ```SWIFT-4.2 ``` successfully on my arm64v8 board, certainly with some modifications.
Now I am wondering whether should I create a tarball of output package and use it in dockerfile or there should be some other approach.

**Comment by florianreinhart** [comment]
@odidev Do the tests pass? There seem to be several issues with Swift 4 on ARM.

https://bugs.swift.org/browse/SR-5845
https://bugs.swift.org/browse/SR-5846

**Comment by odidev** [comment]
I am able to build Swift just in ```release mode```, where test cases are not coming into the picture.
Swift is not working for me in ```test mode```, so not able to pass test cases.

I think we can go ahead at higher pace if somehow I can get useful guidance to resolve pending issues.
I am ready to do experimental changes too, as my goal to see Swift in the official list of ```arm64v8```.

Regards,

**Comment by odidev** [comment]
Hi,

I am actively tracking Swift project for support over ```ARM64v8``` architecture.
Recently I observed that there are other communities which are working aggressively to enhance Swift for ARM.

This is the link of deb which is being maintained by them:
https://packagecloud.io/swift-arm/debian/packages/ubuntu/xenial/swift4_4.1.1_arm64.deb 

I have used this link in my swift-docker to get proper Swift environment and then compiled and run multiple application codes to get desired output.

The above link is resultant of ongoing work on this ticket:
https://github.com/WorksOnArm/cluster/issues/62 

Can this packagecloud.to link be used directly in the Swift Docker and then use it officially for ```arm64v8```?

Regards,

**Comment by lag-linaro** [comment]
Looks as though ARM support for Swift is really progressing.

Would  you guys consider pulling in packages from @futurejones or Works-On-ARM to secure ARM(64) support?

**Comment by odidev** [comment]
This is an update to what I have observed with the latest Swift code base.
The current ```Master Branch``` of Swift is working pretty well over ARM64 architecture as well.

This has been validated by compiling the Swift code in ```release``` mode and then using the interactive shell for running normal programs.
Earlier I was getting errors over the shell but now those are resolved in the current code at ```master```.

In my opinion, the Swift code can support ```arm64v8``` now.
Also, I would suggest creating a branch out of current code and provide support for ```arm64v8``` architecture from there, until we get confirmation.

Regards,

**Comment by lag-linaro** [comment]
Has anyone spoken to the guys over at Swift, to see if they are keen to publish ARM64 packages?

**Comment by odidev** [comment]
Hi @lag-linaro 
Well, I don't have any direct links with Swift community for sure.

Can you please check it internally, please?

Regards,

**Comment by lag-linaro** [comment]
@odidev I can see that **you** do not have links, but maybe one of the other guys here do.

**Comment by shahmishal** [comment]
@lag-linaro We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by lag-linaro** [comment]
Is there anywhere I can place issues which aren't going to be ignored for 9 months?

Ref: https://bugs.swift.org/browse/SR-9500

**Comment by wlisac** [comment]
@lag-linaro I recently brought this topic up on the forums.

https://forums.swift.org/t/swift-docker-images-for-arm-raspberry-pi-etc/24777
