### ISSUE TITLE
Use ubuntu 18.04 to build 4.2 images

### ISSUE THREAD

**Issue by gperdomor** [swiftlang/swift-docker#118]
Please use ubuntu 18.04 in Swift 4.2 images :D

**Comment by ianpartridge** [comment]
I think we should offer all the flavours of Ubuntu that Swift supports, including 18.04 🙂

**Comment by gperdomor** [comment]
@ianpartridge even better

**Comment by shahmishal** [comment]
@gperdomor We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by ianpartridge** [comment]
We aren't going to release any more Swift 4.2 images. We offer 16.04 and 18.04 for Swift 5.
