### ISSUE TITLE
README for REPL example doesn't work

### ISSUE THREAD

**Issue by fekerr** [swiftlang/swift-docker#119]
docker run --cap-add sys_ptrace -it --rm swift swift
error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8

**Comment by shahmishal** [comment]
@fekerr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
