### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by sosedoff** [swiftlang/swift-docker#12]
Hey, thanks for putting together this docker image for swift!
I just added it to BitRun, a small project for coding sandboxes that im running. Works great.
Try it yourself - https://bit.run/try/swift

**Comment by hamin** [comment]
@sosedoff awesome! Good to know its working for you :). @sosedoff I'm gonna close this issue unless there's something else you'd like to add?

**Comment by hamin** [comment]
@swizzlr It might be cool to have our own online version running swift. Bitten looks great. @sosedoff how would you feel like about contributing an online Swift only demo that we can host in this Github Org? Totally fine if you're not up for it :)

**Comment by sosedoff** [comment]
@hamin i dont really want to create another web ui since i already work on bit.run, but you could hack on something very simple using bit.run's API, its open source - https://github.com/bitrun/api. Here's an example curl request to run swift code:

``` bash
curl \
  -i \
  -X POST "https://bit.run/api/v1/run" \
  -d "filename=main.swift&content=print(\"Hello World\")"
```

You'll get something like this:

```
HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Sat, 05 Dec 2015 02:16:36 GMT
Content-Type: text/plain
Content-Length: 13
Connection: keep-alive
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
X-Run-Command: swift main.swift
X-Run-Duration: 293.89573ms
X-Run-Exitcode: 0

Hello World
```
