### ISSUE TITLE
4.2 contains swift 4.2.1

### ISSUE THREAD

**Issue by kondaurovDev** [swiftlang/swift-docker#122]
Hello! Is that correct? I run swift:4.2 but get version 4.2.1 instead of 4.2?

> docker run --rm swift:4.2 swift --version
> Swift version 4.2.1 (swift-4.2.1-RELEASE)
> Target: x86_64-unknown-linux-gnu

**Comment by shahmishal** [comment]
@kondaurovDev We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by ianpartridge** [comment]
Yes it is correct - we support the latest release of each minor version of Swift.
