### ISSUE TITLE
hello！dear， I have a problem in objective-c  please help me !!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by 304164084** [swiftlang/swift-docker#127]
in oc, i get a problem in UICollectionView. When the collectionView item size is a constant. eg CGSizeMake(100, 45). in ar language(阿拉伯语). the collectionView will auto reverse its cells. but if the cell's size is not a constant, it will not auto adapt. I want know is there any property can close the feature? 

大哥你好， 我在Objective-C中的UIKit框架的 UICollectionView中遇到了问题。在阿拉伯语环境下， 当cell的 size 为常量时，系统会自动适配(cell会自动反转)。 但是当size为变量时，这种特性就消失了。 我想问下 这里是否存在个属性来控制这种特性。这个特性给我造成了很多不便。我认为这个设计很不合理。或者不够完善。  期待您的回复！！！ 

   最后最后(Last last last!) 我是实在找不到 在哪里去提问 所以找到了这里， 请见谅！！

**Comment by ianpartridge** [comment]
Hi, I'm afraid you have posted your question in the wrong place.  This repository is for discussion of Swift Docker images.

You should probably post your UICollectionView question at https://developer.apple.com/devforums/
