### ISSUE TITLE
Why not latest ubuntu version?

### ISSUE THREAD

**Issue by huytd** [swiftlang/swift-docker#13]
Why not using latest ubuntu version? It's 15.10 already

**Comment by lexrus** [comment]
It's configurable via ENV after #11 merged.

**Comment by swizzlr** [comment]
@huytd Phusion base image is based on Ubuntu LTS, which is usually considered a sensible choice. We want to control for the one moving target, i.e. swift, and it would suck to have to maintain it if Ubuntu broke for whatever reason.

@lexrus I assume he's talking about the FROM statement. I have my reservations about the phusion base image, but tbh we can change it before we hit 1.0 and call it official.

**Comment by hamin** [comment]
The Ubuntu Version is configurable. Right now going with latest LTS release supported by the official Swift ubuntu builds.
