### ISSUE TITLE
Please add "distroless" images to simplify distribution of Swift apps

### ISSUE THREAD

**Issue by TheIndifferent** [swiftlang/swift-docker#133]
Current images contain all the development libraries, headers and compilers. This is not a good base to distribute Swift applications.

Please add the image variant that can be used as a base image to run applications, that will have only necessary runtime dependencies. "Distroless" concept seem to be the most effective for that:

https://github.com/GoogleContainerTools/distroless

**Comment by ianpartridge** [comment]
> Current images contain all the development libraries, headers and compilers. This is not a good base to distribute Swift applications.

Agreed, but the images are not intended to be a base for distributing Swift applications. They are a "shop front" for Swift, aimed at newcomers to the language who want to explore building apps and running the REPL.

> Please add the image variant that can be used as a base image to run applications, that will have only necessary runtime dependencies. "Distroless" concept seem to be the most effective for that:
> 
> https://github.com/GoogleContainerTools/distroless

I agree that it would be great to have a "runtime" image, but I think Swift's runtime requirements are currently quite considerable, unfortunately. I doubt that https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md would be sufficient.

More likely in the short term is an Ubuntu-based runtime image. Even a "Hello world" Swift program links 63 shared libraries: https://forums.swift.org/t/which-clang-package-should-we-install/20542/8?u=ianpartridge

**Comment by TheIndifferent** [comment]
Thanx for the fast reponse!

> Agreed, but the images are not intended to be a base for distributing Swift applications. They are a "shop front" for Swift, aimed at newcomers to the language who want to explore building apps and running the REPL.

And that is not something on TODO list to provide runtime base images? I would imagine that Swift Server development would definitely benefit from it.

And thanx for the link! Might help me build my own minimal image 😆

**Comment by ianpartridge** [comment]
Yes it's definitely on the TODO list 🙂 

I would also like images based on Debian (rather than Ubuntu).

**Comment by TheIndifferent** [comment]
Going for distroless-style images, from personal experience it is much easier to use `rpm`-based distros, because unlike `deb` they are easier to relocate, to create rootfs with all the dependencies, for example openSUSE:
```
zypper --non-interactive --root /swift-root install --no-recommends coreutils ...
```
Then in `Dockerfile` it will be as easy as
```
FROM scratch
COPY --from=build /swift-root /
CMD ["appname"]
```

So that might be a good enough solution at least in short term.

**Comment by ianpartridge** [comment]
Interesting! I'm not familiar with zypper. Can I suggest you start a discussion on the Docker section of the Swift forums? https://forums.swift.org/c/server/docker

**Comment by TheIndifferent** [comment]
Ok, I will try to come up with something to actually show and not only talk 😆

**Comment by TheIndifferent** [comment]
It seems like there are no quality RPM packages available for Swift, so this might take much longer than I expected.

I did a different experiment, seems like 18.04 version of ubuntu container is supposed to be the smallest one. It is still nearing 250MB with all the deps and Swift runtime libs, but cannot compare it to 700MB of full image:
https://github.com/TheIndifferent/timestampname-swift/blob/master/Dockerfile

**Comment by ianpartridge** [comment]
Yes I think this is the approach to take with the Swift 5 images.

**Comment by ianpartridge** [comment]
Closing this because true distroless images are not feasible in the short term. We're working on `slim`/`runtime` images at the moment though.
