### ISSUE TITLE
Publish 5.2

### ISSUE THREAD

**Issue by twodayslate** [swiftlang/swift-docker#162]
With the official release of [Swift 5.2](https://swift.org/blog/swift-5-2-released/) the docker image should also be pushed.

**Comment by waterskier2007** [comment]
@hamin, @swizzlr, and @Khalian are there plans to get this image in docker hub soon?

edit: apologies if I tagged the wrong users, I consulted project.md

**Comment by waterskier2007** [comment]
It looks like the image has been pushed, however when trying to pull, I am receiving
> no matching manifest for linux/amd64 in the manifest list entries

From searching the error message, it sounds like it may be an issue that resolves itself given some time after the image has been created

**Comment by mattt** [comment]
@waterskier2007 I was experiencing this as well, but this appears to now be resolved (at least on GitHub Actions)

**Comment by waterskier2007** [comment]
resolved on my end as well
