### ISSUE TITLE
do slim images need the swift toolchain?

### ISSUE THREAD

**Issue by tomerd** [swiftlang/swift-docker#181]
afaik the design of the slim images is to include the dependencies needed to *run* swift programs, not to run swift, but we currently include the toolchain in the slim images. is this intentional?

**Comment by tomerd** [comment]
cc @drexin @shahmishal

**Comment by shahmishal** [comment]
Please use bugs.swift.org Component: Docker to file new issues. 

https://github.com/apple/swift-docker/issues/118#issuecomment-446784385

**Comment by shahmishal** [comment]
@tomerd It should not have swift toolchain in the image, the Dockerfile is configured to download the swift toolchain but only install the lib. 
Example from 5.2 Ubuntu 16.04 slim Dockerfile 
```
    # - Unpack the toolchain, set libs permissions, and clean up.
    && tar -xzf swift.tar.gz --directory / --strip-components=1 $SWIFT_VERSION-$SWIFT_PLATFORM/usr/lib/swift/linux \
    && chmod -R o+r /usr/lib/swift \
```
https://github.com/apple/swift-docker/blob/master/5.2/ubuntu/16.04/slim/Dockerfile#L42

**Comment by tomerd** [comment]
ah got it. so we need add slim images for al2 and centos 8 too. https://bugs.swift.org/browse/SR-12963
