### ISSUE TITLE
Publish 5.3

### ISSUE THREAD

**Issue by twodayslate** [swiftlang/swift-docker#183]
When 5.3 is released so should the docker image. Thank you!

**Comment by waterskier2007** [comment]
It will definitely get released, but this is a bit premature as 5.3 is not released outside of the Xcode 12 betas and nightly snapshots. If you need to test it out, you can use the 5.3 tags here https://hub.docker.com/r/swiftlang/swift/tags .

**Comment by twodayslate** [comment]
Why was this closed? I don't see the latest image on docker

**Comment by shahmishal** [comment]
Sorry, it was a mistake!

**Comment by waterskier2007** [comment]
personally I don't think there should be an open issue to publish an image that is not yet a public release, but that's up to @shahmishal

**Comment by twodayslate** [comment]
It's the best way for me to get notified when the 5.3 image is officially released.

**Comment by waterskier2007** [comment]
Utilizing github issues as a personal notification system seems a bit odd. Github issues should represent actual open issues with the repository.

**Comment by twodayslate** [comment]
This issue seems relevant and similar issues have been opened in the past.

**Comment by twodayslate** [comment]
https://swift.org/blog/swift-5-3-released/

Swift 5.3 has officially been released.

**Comment by waterskier2007** [comment]
https://github.com/docker-library/official-images/pull/8736

**Comment by shahmishal** [comment]
Docker images published on https://hub.docker.com/_/swift
