### ISSUE TITLE
Failure to build with current instructions

### ISSUE THREAD

**Issue by schafdog** [swiftlang/swift-docker#211]
Hi 

I am trying to test my Debian docker image with the instructions in swift-ci but this fails very early. The instructions says the command to execute in docker should be: 

/bin/bash -lc "cp -r /source/* /home/build-user/; ./swift/utils/build-script --preset buildbot_linux"

First problem: it fails to copy the files: permission denied. The instruction says it has to be non-root. Which user? docker?

Second problem: With files in place: the next part of the command fails:
~/Projects/swift-source$  ./swift/utils/build-script --preset buildbot_linux
[./swift/utils/build-script] ERROR: no value found for install_destdir in "%(install_destdir)s"

Tried to debug the code but didn't figure out what is missing. This happens both in docker and if I build on command line in the host (also debian 10).Should I use another value for preset and/or configure it somewhere?

**Comment by schafdog** [comment]
Same error with the current ubuntu 20.04 image. So what am I doing wrong?

**Comment by schafdog** [comment]
Looking at the CI builds I can see that there are a number of environment variables passed from the host to docker container. 
and it is show that one is evaluated to --install-destdir=/home/build-user/swift-nightly-install 
But  build-script does not recognise this.

**Comment by schafdog** [comment]
I now see that the docker command is like 

--preset buildbot_linux install_destdir=/home/build-user/swift-nightly-install installable_package=/home/build-user/swift-DEVELOPMENT-SNAPSHOT-2020-11-11-a-ubuntu20.04.tar.gz

That seems to work (at least start) with my Debian-10 image.

**Comment by schafdog** [comment]
It failed later with a cryptic message. I am now trying with all the expanded parameters

**Comment by schafdog** [comment]
It still fails with same error:

/usr/bin/ld: lib/hwasan/CMakeFiles/RTHwasan_dynamic.x86_64.dir/hwasan.cpp.o: relocation R_X86_64_PC32 against undefined symbol `__ehdr_start' can not be used when making a shared object; recompile with -fPIC

Strange It did log earlier it was using -fPIC

**Comment by Fwwq** [comment]
> Hi 
> 
> 
> 
> I am trying to test my Debian docker image with the instructions in swift-ci but this fails very early. The instructions says the command to execute in docker should be: 
> 
> 
> 
> /bin/bash -lc "cp -r /source/* /home/build-user/; ./swift/utils/build-script --preset buildbot_linux"
> 
> 
> 
> First problem: it fails to copy the files: permission denied. The instruction says it has to be non-root. Which user? docker?
> 
> 
> 
> Second problem: With files in place: the next part of the command fails:
> 
> ~/Projects/swift-source$  ./swift/utils/build-script --preset buildbot_linux
> 
> [./swift/utils/build-script] ERROR: no value found for install_destdir in "%(install_destdir)s"
> 
> 
> 
> Tried to debug the code but didn't figure out what is missing. This happens both in docker and if I build on command line in the host (also debian 10).Should I use another value for preset and/or configure it somewhere? 
> 
>
