### ISSUE TITLE
SWIFT_SIGNING_KEY expires in a week

### ISSUE THREAD

**Issue by tombailey** [swiftlang/swift-docker#227]
According to [this](https://github.com/apple/swift-docker/blob/main/5.1/ubuntu/18.04/slim/Dockerfile#L15 ), the SWIFT_SIGNING_KEY is going to expire in a week. Is that going to cause any problems?

**Comment by shahmishal** [comment]
Signing Key renewed - https://github.com/apple/swift-docker/pull/228
