### ISSUE TITLE
the focal-slim image do not have `swift` binary

### ISSUE THREAD

**Issue by bytemain** [swiftlang/swift-docker#229]
![image](https://user-images.githubusercontent.com/13938334/115010972-a602db00-9ee0-11eb-9b18-f7cabb476bc5.png)

**Comment by 0xTim** [comment]
This is expected. The `-slim` images are purely for _running_ Swift applications, not compiling them or running the REPL. The idea is that they fix into multistage Dockerfiles, so you use the non-slim version to compile your application, copy it over to the slim container and then run it from there. If you want to run the REPL or compile code you need the full container
