### ISSUE TITLE
Unicode in REPL

### ISSUE THREAD

**Issue by mikeknep** [swiftlang/swift-docker#28]
I'm unable to type or paste from clipboard Unicode characters like £ (via `option 3` on OSX) or ≈ (`option x`) inside the Swift 3 repl running in Docker. I noticed that by default I can't type these characters into a bash shell inside this container at all unless adding the environment variable `-e "LANG=C.UTF-8"`, which [apparently](http://stackoverflow.com/questions/25637292/cannot-type-unicode-in-a-ubuntu14-04-container-can-type-just-fine-in-busybox) is related to the base ubuntu image. However, even with that env var provided and working in bash, the unicode characters still won't appear in the Swift repl.

Some basic versions (can provide more detail as needed):

```
$ docker-machine version
docker-machine version 0.6.0, build e27fb87

$ docker -v
Docker version 1.10.3, build 20f81dd
```

Command to start bash / Swift repl:

```
$ docker run -it --rm --privileged=true -e "LANG=C.UTF-8" swiftdocker/swift [bash|swift]
```

I have no trouble typing these characters into a Swift 2.2 repl running locally, installed via Homebrew

**Comment by hamin** [comment]
@mikeknep not sure what the exact issue is, but I'll try to replicate it this weekend and take a look at it. If you figure it out feel free to update the issue or submit a PR :)

**Comment by hamin** [comment]
Closing this issue. These problems I think have long been solved. Happy to reopen if anyone else is still running into this issue.

**Comment by mikeknep** [comment]
I'm still having this issue exactly the same as initially described. It's hardly mission critical so I don't mind the issue being closed, but I figured I'd report my experience here in case someone else runs into this.

**Comment by hamin** [comment]
@mikeknep did you try `--privileged=true`?

**Comment by mikeknep** [comment]
@hamin yep. Using the latest image (`72a024daf2ad`).

```
$ docker run -it --rm --privileged=true -e "LANG=C.UTF-8" swiftdocker/swift bash
root@...:/# £££
root@...:/# swift
1> (unable to type £)
```
