### ISSUE TITLE
[SR-16117] Swift default Dockerimage should depend on ubuntu 22.04 (jammy) 

### ISSUE THREAD

**Issue by fabianfett** [swiftlang/swift-docker#281]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-16117      |
   |Radar             | None         |
   |Original Reporter | @fabianfett      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 1         |
   |Component/s       | Docker    |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   

   md5: 04be5bcbf02fb803bfbe22b092f39455

  </details>

**Issue Description:**

The current default Swift `Dockerimage` uses ubuntu bionic as the underlying os. Since Swift only supports arm64 starting with focal, users on arm processors can not use `docker run swift`. Instead they need to explicitly require focal: `docker run swift-focal`. With the next ubuntu lts release around the corner 22.04 ("jammy"), we want the default Swift `Dockerimage` to depend on "jammy" directly for Swift 5.7.

**Comment by fabianfett** [comment]
@swift-ci create

**Comment by shahmishal** [comment]
Jobs created: 
* https://ci.swift.org/job/oss-swift-package-ubuntu-22_04/
* https://ci.swift.org/job/oss-swift-package-ubuntu-22_04-aarch64/

**Comment by shahmishal** [comment]
Swift default is Ubuntu 22.04 - [5.9.1, 5.9, 5.9.1-jammy, 5.9-jammy, jammy, latest](https://github.com/apple/swift-docker/blob/df8e8e36df704e52b2fabf9e732a0f08fbb333e4/5.9/ubuntu/22.04/Dockerfile)
