### ISSUE TITLE
[SR-12963] add slim images for centos8 and Amazon Linux 2

### ISSUE THREAD

**Issue by tomerd** [swiftlang/swift-docker#286]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12963      |
   |Radar             | None         |
   |Original Reporter | @tomerd      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Docker    |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   

   md5: 3025bc9c7a10bf127b32be7b5252c596

  </details>

**Issue Description:**

we currently do not offer slim images for centos8 and Amazon Linux 2, but we do for ubuntu. we should offer slim images for all linux variants

**Comment by shahmishal** [comment]
We have slim image for [5.9.1-amazonlinux2-slim, 5.9-amazonlinux2-slim, amazonlinux2-slim](https://github.com/apple/swift-docker/blob/df8e8e36df704e52b2fabf9e732a0f08fbb333e4/5.9/amazonlinux/2/slim/Dockerfile)
