### ISSUE TITLE
[SR-10039] Docker Hub not updated for 4.2.3

### ISSUE THREAD

**Issue by grahamburgsma** [swiftlang/swift-docker#293]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-10039      |
   |Radar             | None         |
   |Original Reporter | @grahamburgsma      |
   |Type              | Bug    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Docker    |
   |Labels            | Bug        |
   |Assignee          | @shahmishal      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: 716646adf9db0c12ec661caf9485f528

  </details>

**Issue Description:**

Docker Hub has not been updated for the latest 4.2.3 release.

<https://hub.docker.com/_/swift>

**Comment by grahamburgsma** [comment]
@weissi pinging you here since you tagged the GitHub release and posted the announcement.

**Comment by weissi** [comment]
Thanks @grahamburgsma, my PR (<https://github.com/apple/swift-docker/pull/132)> to update to 4.2.3 was actually merged but I'm unsure what exactly triggers the Docker Hub update. @shahmishal?

**Comment by shahmishal** [comment]
Swift 4.2.3 is now available on [https://hub.docker.com/\_/swift](https://t.co/cvWww0IBXP)

<https://twitter.com/mishaldshah/status/1103082532839419905>
