### ISSUE TITLE
[SR-9924] Add Dockerfiles for all Linux supported target platforms

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-docker#294]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-9924      |
   |Radar             | None         |
   |Original Reporter | sja26 (JIRA User)      |
   |Type              | Task    |
   |Status            | Resolved        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Docker    |
   |Labels            | Task        |
   |Assignee          | sja26 (JIRA)      |
   |Priority          | Medium      |

   Watchers: @shahmishal

   md5: 8afd3d6e9b4032d916e78f197ec0c0a8

  </details>

**Issue Description:**

<https://hub.docker.com/_/swift> lists Dockerfiles that use Ubuntu 16.04. Since the supported target platforms also include 14.04 and 18.04, I would expect Dockerfiles to exist for these too.

A Dockerfile that uses Ubuntu 18.04 exists <https://github.com/apple/swift-docker/blob/master/4.2/ubuntu/18.04/Dockerfile> but is not listed <https://hub.docker.com/_/swift> 

See original issue <https://github.com/apple/swift-docker/issues/118>

**Comment by shahmishal** [comment]
Docker images for Ubuntu 16.04 and 18.04 are available on  <https://hub.docker.com/_/swift> now.
