### ISSUE TITLE
swift-build doesn't work in container anymore

### ISSUE THREAD

**Issue by ddunbar** [swiftlang/swift-docker#30]
It looks like you can't use the package manager inside the swift docker container anymore, because the lib curl dependency isn't present:

```
$ docker images | grep swiftdocker
swiftdocker/swift        latest              d366469c2806        5 hours ago         988.3 MB

$ docker run -ti swiftdocker/swift

root@5cda607f685c:/# swift --version
Swift version 3.0-dev (LLVM f54fa77021, Clang 9a77bc41b8, Swift 1a88c86f39)
Target: x86_64-unknown-linux-gnu

root@5cda607f685c:/# swift build --help
/usr/bin/swift-build: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by hamin** [comment]
@ddunbar that's interesting, is that a recent change in swift build? I thought we were installing al the dependencies already. If you could submit a PR that would be great. I am volunteering at the Try Swift NYC conference today and Tommorrow so won't be able to get to it till tomorrow night probably. Thanks for reporting :)

**Comment by ddunbar** [comment]
Swift in general started depending on this in Foundation I believe.

I don't think I'll be able to submit a PR any time soon, just wanted to
report it!

**Comment by hamin** [comment]
@ddunbar no worries thanks for reporting I will try it later this week

**Comment by hamin** [comment]
@ddunbar do you know which version of curl/libcurl Foundation is using? I was unable to figure that out. I did a simple `apt-get install curl` in the docker container and SPM is working again. But I want to make sure I add the official compliant version of curl/libcurl in the main Dockerfile.
