### ISSUE TITLE
Guess snapshot version is wrong

### ISSUE THREAD

**Issue by digidhamu** [swiftlang/swift-docker#31]
I believe snapshot version should be `DEVELOPMENT-SNAPSHOT-2016-09-06-a` rather `DEVELOPMENT-SNAPSHOT-2016-09-02-a`. Please advise.

**Comment by hamin** [comment]
It's actually correct. I'm just falling behind on keeping up on nightly development snapshots. Need to still do the official swift 3 release snapshot. We need to version similar to standard docker versioning but I"m not super familiar with doing it myself. Any help would be appreciated. Will leave this issue open for further discussion
