### ISSUE TITLE
Nightly centos7 and bionic images not pushed recently

### ISSUE THREAD

**Issue by patrickfreed** [swiftlang/swift-docker#326]
The `nightly-centos7` and `nightly-bionic` images were last pushed 7 months ago even though the most recent snapshot was only a few days ago. Is this intentional?

- https://hub.docker.com/layers/swiftlang/swift/nightly-bionic/images/sha256-636a42df6785d6b069f453ec848f2cd9d54a879edfda54d924dd69d775c9c87f?context=explore

- https://hub.docker.com/layers/swiftlang/swift/nightly-centos7/images/sha256-5f76ae7f29792f819e8f30c5396580ea930c1ae449b91e4c9c9137e4f1c3e2ca?context=explore

**Comment by shahmishal** [comment]
This issue was resolved while ago, never updated here.
