### ISSUE TITLE
Swift 3.0 Docker image tag

### ISSUE THREAD

**Issue by cloutiertyler** [swiftlang/swift-docker#34]
Can we get a tag for the official Swift 3.0 release on Dockerhub?

**Comment by hamin** [comment]
@TheArtOfEngineering  Added 3.0.0 tag on docker hub https://hub.docker.com/r/swiftdocker/swift/builds/bycyuaqmmkt9mza5ybxslpm/

Also added 3.0.1 tag should be on docker hub soon too :)

Enjoy :)
