### ISSUE TITLE
git commit history seems messed up

### ISSUE THREAD

**Issue by Khalian** [swiftlang/swift-docker#44]
My commits appear twice after the last merge.

**Comment by Khalian** [comment]
https://github.com/swiftdocker/docker-swift/pull/43/commits. IIRC I had exactly one commit and I was squashing it multiple times as the reviews came in. @swizzlr put a new commit on top with an incorrect rebase. The PR then became 5 commits which was then merged and hence the merge was wrong.

**Comment by swizzlr** [comment]
@Khalian I don't have it buddy. What change was it that you wanted to include?

**Comment by Khalian** [comment]
Look at commit https://github.com/swiftdocker/docker-swift/commit/0e5155f56aa083f35ca20e73a124610b2eeb9494 and https://github.com/swiftdocker/docker-swift/commit/267d5d98749ebdaee07b7291f30b636f8ca9c191. They are the same thing and both are in mainline. This does not happen with a proper rebase/merge of a PR.

**Comment by swizzlr** [comment]
Ok. Don't know how that happened. Is there a patch that I overwrote? Otherwise I think we're fine.

**Comment by Khalian** [comment]
No the content looks alright, although I am of the opinion certain commits need to be squashed. But then again the HEAD branch is already corrected and we expose a misplaced master branch to our consumers.
