### ISSUE TITLE
Alternative working base image to Ubuntu

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#47]
The slim compiler image doesn't need full Ubuntu if we can get away with it.

To try:
- [ ] busybox
- [ ] other slim Debian images?
- [ ] ??

The base image MUST be an official Docker image.

**Comment by hamin** [comment]
I would love to try that but it would be it wresting getting entire llvm and c deps on alpine, I know historicallybalpine had issues with it but it's way better now from friends that I know. So yeah let's give t a shot but we would have to do most work I think. Not sure how much swift org will be able to help. But yeah let's do it

**Comment by swizzlr** [comment]
Okay, three things:
1. Investigate reducing number of packages
2. Investigate smaller clang/llvm (can we drop the lldb/repl?)
3. Investigate buildpack-deps/alpine

**Comment by hamin** [comment]
all sounds good... i'd love to keep the repl still...hmm dunno

**Comment by swizzlr** [comment]
@hamin not for an alpine variant we don't have to. this would be a version for distributing swift apps

**Comment by hamin** [comment]
@swizzlr agreed for alpine we can skip lldb/repl. Sounds like a plan

**Comment by aidansteele** [comment]
I think an Alpine variant is going to be difficult. Alpine's CRT is musl instead of glibc. Swift makes the assumption right now that Linux == glibc. There are variants of Alpine using glibc, but they are unsupported and then you lose out on a lot of the packages in the Alpine ecosystem which assume musl.

There has been some research into it on the mailing lists: https://lists.swift.org/pipermail/swift-users/Week-of-Mon-20151228/000653.html

**Comment by swizzlr** [comment]
So it seems like we're stuck until somebody can port Swift. Maybe we should investigate Busybox Glibc?

**Comment by aidansteele** [comment]
Busybox w/ glibc sounds like a really promising idea 👍 That said, I'm not super familiar with the Busybox world of packages - is it as popular as Ubuntu/Alpine?

**Comment by swizzlr** [comment]
As I recall Busybox used to be v popular before Alpine among Docker users. Could be a safe bet.

**Comment by e-kazakov** [comment]
IBM has `ibmcom/swift-ubuntu-runtime` image without build tools.
But I had problems with their [Dockerfile](https://github.com/IBM-Swift/swift-ubuntu-docker/blob/master/swift-runtime/Dockerfile) and had to [update it](https://gist.github.com/azeff/906e13adca0df3e20b6d68c93ce69754) before I was able to run my kind of 'Hello Word' app.

It's not `alpine`, but still much smaller than `_/swift` image.
```
swiftruntime                  latest              044183a8985a        5 minutes ago       245 MB
swift                         latest              d447e9641510        2 weeks ago         1.06 GB
```

**Comment by swizzlr** [comment]
@azeff could be a good starting point, but I'd really like an image that can compile as well.

**Comment by e-kazakov** [comment]
Uh, I see. I'm looking for image to run vapor app.

**Comment by swizzlr** [comment]
@azeff This is a good use case. I've been working on something similar at work. I hope to be able to share it soon.

**Comment by swizzlr** [comment]
This issue is being refocussed around the base image for the slim-compiler flavor of this image. Any suggestions as an alternative to Busybox and Ubuntu?

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by ianpartridge** [comment]
This issue is very old - please reopen if it's still a problem.

**Comment by iheart2code** [comment]
Looks like the equivalent ticket might be [SR-4632](https://bugs.swift.org/browse/SR-4632).
