### ISSUE TITLE
Document how to build in a docker container and export static binary to a new container

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#48]

**Comment by hamin** [comment]
So are we officially under docker official images imbrella on docker hub now?

**Comment by swizzlr** [comment]
@hamin no, but soon hopefully!

**Comment by swizzlr** [comment]
Getting a lot of +1s on this; depends on #55 since master currently has this ability but 3.0 does not with -static-executable flag.

Might be also worth exploring semi-static variants where libicu and other big libraries are vendored in a tiny base image.

**Comment by helje5** [comment]
I don't think there is a strong requirement for a static binary, the idea is just that the deployment image doesn't carry compilers and such. That doesn't depend on a -static-executable flag (though obviously this makes stuff easier :-)

Pretty much the same thing you have in Linux package management, runtime packages and -dev packages which contain headers etc.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by ianpartridge** [comment]
This issue is very old - please reopen if it's still a problem.
