### ISSUE TITLE
Upgrade Clang?

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#49]
We're pinning to 3.6 right now, should it be 3.8 or even 4.0? Let's check in with CI and dev team.

**Comment by Khalian** [comment]
https://github.com/swiftdocker/docker-swift/pull/58

**Comment by glessard** [comment]
I tried to add nullability annotations to a C header used by a swiftpm project, but this didn't compile in the swift-docker image. It had worked in a local Ubuntu-16 installation, where
```
ubuntu16 [/tmp]$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
ubuntu16 [/tmp]$ swift --version
Swift version 3.0.2 (swift-3.0.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```
Nullability first appears in the clang 3.7.0 documentation as far as I can tell.

**Comment by Khalian** [comment]
@glessard I see, I will try to push to merge this in.

**Comment by Khalian** [comment]
Can we close this ?

**Comment by glessard** [comment]
Could the `3.1` and `latest` tags be updated? After that happens, by all means.

**Comment by swizzlr** [comment]
superseded by #92
