### ISSUE TITLE
Automated images based on new snapshots

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#50]
If we can get an RSS feed or something of new snapshots, we can auto push new snapshots for access to preview versions of Swift.

**Comment by hamin** [comment]
@swizzlr that would be awesome...would make it way easier to play with latest snapshots...I think swift team is doing nightly snapshots now... but yes some api/rss feed or whatever would be great. Another thing to discuss with swift core community

**Comment by swizzlr** [comment]
Whoever's running Swift CI could let us know – perhaps there's a jenkins plugin.

**Comment by mackoj** [comment]
Hi, we can get all new snapshots from this feed https://github.com/apple/swift/releases.atom.

**Comment by swizzlr** [comment]
Are those precompiled or just a source tree?

**Comment by mackoj** [comment]
This rss feed represent each tag so it's only source code. If Apple provide precompiled version directly on Github you could access it with https://developer.github.com/v3/repos/releases/#get-a-single-release.

**Comment by swizzlr** [comment]
Apple provide nightly snapshots from their Jenkins on the website. We need some way of retrieving the latest snapshot's URL/name.

**Comment by aidansteele** [comment]
Each one of the snapshots listed on GitHub (on the Atom feed linked above) has a corresponding binary at `https://swift.org/builds/development/ubuntu1604/swift-$TAG/swift-$TAG-ubuntu16.04.tar.gz`. 

I'd be happy to submit some PRs to a) have a build arg to (default) build releases or build nightlies and b) automating the building and publishing of nightlies. Is that something that would be accepted?

**Comment by hamin** [comment]
@aidansteele that sounds great but I think we're waiting to hear back from some folks at apple/swift core team to see if they can provide any deeper integration. @swizzlr correct me if I'm wrong

**Comment by swizzlr** [comment]
@hamin true but tbh I doubt it's going to be much fancier than that. We can get going on this I think in the meantime.

@aidansteele submit away. How do you propose we automate this? Jenkins?

**Comment by aidansteele** [comment]
@swizzlr I'm a big fan of Jenkins and use it for all my personal projects, but the problem is hosting. I'm not aware of any free hosted Jenkins services for OSS projects, e.g. like Travis. 

I would be more than happy to host this project's CI on the Jenkins server I'm using for http://github.com/awswift, but that would introduce a dependency on me and it'd make sense for others to be uncomfortable with that. So maybe Travis is the way ahead?

**Comment by swizzlr** [comment]
My only issue with Travis is scheduling. For now I'm happy to front the cost of deployment, or for you to do so, until such time as perhaps we can integrate with the Swift Jenkins.

**Comment by Khalian** [comment]
@aidansteele I already hosted it on shippable : https://app.shippable.com/projects/58663bf6f6c7101000c4038f/builds/latest which is better than travis for docker builds. I will take a look at RSS notifications from shippable whenever I get the time.

**Comment by Khalian** [comment]
Following up with shippable support : https://github.com/Shippable/support/issues/3331

**Comment by aidansteele** [comment]
I'm not sure I follow. How would RSS notifications from shippable be helpful? We don't need a feed of the Docker images being built, but triggering CI jobs for this project from new entries in the upstream Swift language release RSS feeds.

**Comment by Khalian** [comment]
" but triggering CI jobs for this project from new entries in the upstream Swift language release RSS feeds"

So the RSS feeds are on release candidates and not on the CI pipeline? I dont see the rationale of putting an RSS feed on manually triggered builds.

**Comment by swizzlr** [comment]
This is a dupe of #55 .
