### ISSUE TITLE
Investigate reducing number of packages

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#51]
Can we get away with less packages? Any of them redundant? rsync, libxml2?

**Comment by Khalian** [comment]
I was able to remove rsync. https://github.com/swiftdocker/docker-swift/pull/63

I want to keep libxml2, since its a pretty core package and tons of other libraries use it. Rsync is just a command line utility.

**Comment by Khalian** [comment]
Removing cmd utils post installation : https://github.com/swiftdocker/docker-swift/pull/69

**Comment by swizzlr** [comment]
Closing this for now, since we've probably done what we can for the time being.
