### ISSUE TITLE
Remove LLDB/REPL

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#52]
We should find a way of installing Swift and removing LLDB and the REPL.

**Comment by Khalian** [comment]
I presume we can, but lldb is not a separate package we use in the installer so I am unsure at which point we can drop it. Why do we wish to drop repl support ?

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
