### ISSUE TITLE
Investigate buildpack-deps/alpine

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#53]
Can we make an image that works on this instead? Do we need to recompile a custom flavour of swift that'll work on a non-debian distribution?

**Comment by swizzlr** [comment]
First step – let's try to build this on alpine and see about the file size difference.

**Comment by Khalian** [comment]
I gave it a shot. While the whole thing builds, there is an ABI mismatch. Swift is not runnable in Alpine at this point.

**Comment by swizzlr** [comment]
We need to recompile it against muslibc I guess?

**Comment by aidansteele** [comment]
I might have posted this in the wrong issue, but I made a comment re: compiling Swift against musl here @swizzlr: https://github.com/swiftdocker/docker-swift/issues/47#issuecomment-275280880

**Comment by swizzlr** [comment]
@aidansteele cheers. closing this in favour of #47
