### ISSUE TITLE
Automated generation of new Dockerfiles and images

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#55]
Currently every new release requires manual generation of new Dockerfiles and images.

Continuous integration using Travis CI, the RSS feed from the releases page and the nightly snapshots would allow this to happen.

Anybody want to take this on?

**Comment by Khalian** [comment]
Any tutorials on how to do this ?

**Comment by hamin** [comment]
no tutorials... i think a while ago we figured that we could get some sort of notification from swift build releases...i think ppl on swift mailing list liked the idea, but i don't think we got a follow up on it

**Comment by andradei** [comment]
We should get this going :)

**Comment by florianreinhart** [comment]
Docker’s guidelines for official images advise against creating images from CI builds:

> Unlike a release candidate, continuous integration builds which have a fully automated release cycle based on code commits or a regular schedule are not appropriate.

https://github.com/docker-library/official-images#library-definition-files

Nevertheless, it’d be great to test current development snapshots of a specific version branch, e.g. Swift 4.2. Maybe these builds could be considered “release candidates”.

Can someone check this with the official images maintainers?

**Comment by norio-nomura** [comment]
FYI, my repository([norionomura/swift](https://hub.docker.com/r/norionomura/swift/)) has been automated for Dockerfile update and image creation by using [CircleCI 's scheduled workflow](https://circleci.com/gh/norio-nomura/workflows/docker-swift).

**Comment by andradei** [comment]
@florianreinhart If I understand that document correctly, _regular schedules_ aren't appropriate. How about some sort of automated script that checks whether a new version was released (not new commits, but full-fledged releases) and builds a new docker image?

**Comment by florianreinhart** [comment]
It's OK to automatically generate a new image whenever a new Swift version is released.

I am just not sure about the Swift development releases generated from a development branch like [swift-4.2-branch](https://github.com/apple/swift/tree/swift-4.2-branch). These are generated by Swift CI almost every day.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
