### ISSUE TITLE
Image for ARM (armhf)

### ISSUE THREAD

**Issue by krystiansliwa** [swiftlang/swift-docker#56]
Hi,
are there any plans to have official docker image for ARM devices?

**Comment by swizzlr** [comment]
Since ARM isn't officially supported by the Swift project I think it would be out of scope for this project to simultaneously support Swift on ARM and a docker image based on that. While I'm very interested and supportive of this effort, perhaps we should create an experimental image under this organisation - Docker Swift ARM?

**Comment by krystiansliwa** [comment]
I found some docker iamge for armhf Ubuntu 16.04, and compiled Swift with 3.0.2 version. Maybe this is a good point to start? What do you think?

**Comment by swizzlr** [comment]
Please share what Dockerfile have in a repository!

**Comment by krystiansliwa** [comment]
I found that repo: https://hub.docker.com/r/armv7/armhf-ubuntu/

**Comment by swizzlr** [comment]
I mean that plus the instruction for how to build an ARM docker image.

One thing: I doubt we can offer this under the official repo - we need the base image to be an official repo too, unless it's FROM scratch.

**Comment by krystiansliwa** [comment]
Unfortunately currently there are only "experimental" images [according this info](https://github.com/docker-library/official-images).

**Comment by swizzlr** [comment]
Okay, well if you could contribute a Dockerfile that produces an ARM image with working Swift then we can have a look!

**Comment by krystiansliwa** [comment]
Ok, I will try and let you know about results ;)

**Comment by helje5** [comment]
Doesn't have arm64, but might still be useful: [dockSwiftOnARM](https://github.com/helje5/dockSwiftOnARM/)

**Comment by swizzlr** [comment]
I don't think this is something many people have stepped forward and asked for, nor something that others have offered to support. I'm closing this issue for now, however I strongly encourage anyone passionate about running Swift on ARM Linux to bring us a working Dockerfile. If you do so, it will have a home here.

**Comment by helje5** [comment]
Well, my Dockerfile is working just fine. At least for Swift 3.1. Swift 4 is still stuck. So how would you suggest to go forward with this? Another Dockerfile as a PR, moving over dockSwiftForArm into the `swiftdocker` org?

**Comment by swizzlr** [comment]
@helje5 I was entirely mistaken – we can support multiple architectures.

If you're willing to support arm, we'd be happy to have it. I assume we need a separate Dockerfile? Please propose it as a PR inside `3.1/arm64`.

**Comment by swizzlr** [comment]
For other contributors, we can make this official: https://github.com/docker-library/official-images#multiple-architectures

**Comment by helje5** [comment]
I think the core problem is that swift.org provides no ARM packages. So either you compile Swift from the source (which I can do in Docker), or you pickup a tarball from somewhere non-standard. Not sure what we would want here.

**Comment by swizzlr** [comment]
@helje5 If you're ok with maintaining them. Can you define a Dockerfile that compiles it?

**Comment by shahmishal** [comment]
@krystiansliwa We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).

**Comment by ianpartridge** [comment]
This issue is very old - please reopen if it's still a problem.

**Comment by colemancda** [comment]
@krystiansliwa I've created scripts to cross compile the Swift 5.7 runtime (Not the entire compiler) from x86 or Arm64 to Armv7. You can also cross compile SwiftPM packages from macOS and deploy to Debian 11 armhf.

https://github.com/colemancda/swift-armv7
https://hub.docker.com/repository/docker/colemancda/swift-armv7

- Debian 11 docker with Swift 5.7 runtime installed 
[`colemancda/swift-armv7:5.7-debian11`](https://hub.docker.com/layers/colemancda/swift-armv7/5.7-debian11/images/sha256-51871d7e348de5a93e8a4f3ce00daf1a84f334d8203a55c50b54c92ea9a39654?context=repo)

- Cross compilation environment
[`colemancda/swift-armv7:latest`](https://hub.docker.com/layers/colemancda/swift-armv7/latest/images/sha256-6e64d7bb48f40abf78ae3497caebb3e2bef4fa4f2da4f87bb646160847f40443?context=repo)
