### ISSUE TITLE
Run apt-get clean at the end of the installation

### ISSUE THREAD

**Issue by alblue** [swiftlang/swift-docker#57]
You should run 'apt-get clean' at the end of the apt-get installation process; this will remove any downloaded .tgz files which are no longer needed from /var/cache/apt

**Comment by swizzlr** [comment]
This isn't necessary. We used to have this in but ubuntu base image does this automagically: https://github.com/tianon/docker-brew-ubuntu-core/blob/9c78896fe39d5be95cc4a6ae6c0475599a1bc396/xenial/Dockerfile#L21-L24
