### ISSUE TITLE
[RFC] Construct swift versions using environment variables

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#6]
Less duplication, it seems. cf. https://github.com/OliverLetterer/swift-docker/blob/master/Dockerfile

**Comment by hamin** [comment]
this makes perfect sense @OliverLetterer you wanna do this? If not i can submit PR

**Comment by OliverLetterer** [comment]
Sorry for bailing out yesterday without notice, had to really get some sleep. Would have loved to submit a pull request for this but I see there is already #11 :)

**Comment by swizzlr** [comment]
Closed by #14
