### ISSUE TITLE
swift:latest - Import modules fails with can't find stddef.h

### ISSUE THREAD

**Issue by cowlike** [swiftlang/swift-docker#67]
Version 3.0.2 works but latest (3.1) does not. 

<pre>
System is Windows 10
PS C:\> docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
</pre>

How to reproduce:
<pre>
$ docker run --privileged=true --rm -it swift:3.0.2 swift
Welcome to Swift version 3.0.2 (swift-3.0.2-RELEASE). Type :help for assistance.
  1> import Glibc
  2> random()
$R0: Int = 1804289383

$ docker run --privileged=true --rm -it swift:latest swift
Welcome to Swift version 3.1 (swift-3.1-RELEASE). Type :help for assistance.
  1> import Glibc
<module-includes>:3:10: note: in file included from <module-includes>:3:
#include "///usr/include/utmp.h"
         ^
 
///usr/include/utmp.h:23:10: note: in file included from ///usr/include/utmp.h:23:
#include <sys/types.h>
         ^
 
error: /usr/include/x86_64-linux-gnu/sys/types.h:146:10: error: 'stddef.h' file not found
#include <stddef.h>
         ^
 
error: could not build Objective-C module 'SwiftGlibc'
</pre>

**Comment by swizzlr** [comment]
This is strange. It seems to be an issue in the REPL, since it's been working with compiled stuff. We should look into this further. Can it be reproduced outside of Docker, on "raw" Linux?

**Comment by cowlike** [comment]
I don't have a Linux box handy to try it on at the moment. I did verify that it looks good from the compiler. I mounted a local folder with a simple program in *random.swift*:
<pre>
import Glibc
print("random = \(random())")
</pre>
and then I ran it with:
<pre>docker run --rm -v /c/src:/root/src swift:latest swift /root/src/random.swift</pre>

got the expected output.

**Comment by ritalin** [comment]
FYI workaround 

```
docker run --privileged -it --rm swift:latest swift -I/usr/lib/swift/clang/include/
```

reference from: https://bugs.swift.org/browse/SR-3648

**Comment by cowlike** [comment]
Thanks for that workaround. I verified that it does work on Windows 7 and Windows 10.

**Comment by hamin** [comment]
@ritalin thank you for the solution! we'll keep track of it
