### ISSUE TITLE
[RFC] Untar directly into root

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#7]
We can untar directly into the root of the filesystem, so no path modification nor rsync. I think it's slightly more elegant.

https://github.com/swizzlr/docker-swift/blob/master/Dockerfile#L9

**Comment by hamin** [comment]
@swizzlr I guess i'm worried that files folders that exist in /usr don't get overwritten and that we're merely merging the swift related stuff in /usr

**Comment by swizzlr** [comment]
Well, if swift vendors a patched version of anything, we want that in the path, at the very least. With rsync Swift may end up linking to the unpatched version, right? Shall we give it a try and see how it turns out, or should we just dump it all in a private folder and add it to the $PATH?

**Comment by swizzlr** [comment]
(i'm more in favour of installing to root because then you can easily write /usr/bin/swift) etc.

**Comment by hamin** [comment]
@swizzlr ok lets do this. You have me convinced :)

**Comment by hamin** [comment]
@swizzlr i'll submit PR

**Comment by swizzlr** [comment]
go 4 it

**Comment by akatz** [comment]
Also while your doing that, if you combine the commands into one via `&&` and then follow them with `&& rm -rf ...` you don't have a bloated intermediate layer. The cleanup here is nice, but since it happens in a layer further down it's a little bit too little too late.

**Comment by hamin** [comment]
@akatz checkout #14 which reduces layers count. Its been merged into master already. Feel free to open a new issue to suggest more cleanup :). Also nice to see you here buddy :)
