### ISSUE TITLE
建议把openssl和uuid加入镜像。

### ISSUE THREAD

**Issue by kingwangboss** [swiftlang/swift-docker#73]
建议把openssl和uuid加入镜像。

**Comment by Khalian** [comment]
Sorry but we cant read chinese.

**Comment by swizzlr** [comment]
"It is recommended to add openssl and uuid to the mirror."

@kingwangboss 你可以给代码示例吗 – "can you give a code sample?"

**Comment by kingwangboss** [comment]
apt-get update && apt-get install uuid-dev && apt-get install openssl && apt-get install libssl-dev

每次我使用这个镜像部署swift服务都需要先安装这些，然后我自己制作了一个镜像，在你们镜像加入了一层。
Every time I use this image to deploy swift services you need to install these, and then I made a mirror, in your mirror joined a layer.

**Comment by swizzlr** [comment]
superseded by #91
