### ISSUE TITLE
Shared library lookup path is not setup for Swift

### ISSUE THREAD

**Issue by helje5** [swiftlang/swift-docker#75]
When you try to run a Swift binary which is linked dynamically, it won't find the Swift shared libraries in the current Docker image.

You may want to add this:

```Dockerfile
RUN bash -c "echo '/usr/lib/swift/linux' > /etc/ld.so.conf.d/swift.conf;\
             echo '/usr/lib/swift/clang/lib/linux' >> /etc/ld.so.conf.d/swift.conf;\
             echo '/usr/lib/swift/pm' >> /etc/ld.so.conf.d/swift.conf;\
             ldconfig"
```

**Comment by swizzlr** [comment]
@helje5 Just following up: what exactly is needed here? I've used dynamic libs, I think, in the Swift docker image and have had no problems. What are these search paths providing us with?

(n.b. I have no objection to this, I just want to understand more before proceeding.)

**Comment by helje5** [comment]
Let me retry with the current image, not sure yet when I find the time. I think the issue was that the Swift shared libraries are located in the (non-standard) paths above and hence cannot be located by ld.so when running such a program.

**Comment by swizzlr** [comment]
@helje5 Are you trying to link your compiled program against the Swift package manager, etc.?

**Comment by helje5** [comment]
No, just against Dispatch, Foundation and such. The basics.

**Comment by helje5** [comment]
I don't remember what exactly I was doing. Need to review what I did and what didn't work. But I think if you compile a Swift with plain `swiftc`, it'll pickup the .so's and then won't run. Or sth like this, not sure.

**Comment by swizzlr** [comment]
no worries, let us know what we can do to help if the need remains with the latest version.

**Comment by shahmishal** [comment]
@helje5 We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
