### ISSUE TITLE
Instructions on hub.docor.com/r/_/swift/ incorrect

### ISSUE THREAD

**Issue by rayfix** [swiftlang/swift-docker#80]
https://hub.docker.com/r/_/swift/  states:

`docker run --cap-add sys_ptrace -it --rm swift swift`

However, this doesn't actually work.  You need `--privileged`

Also,
```
docker run  -it --name swiftfun swift:latest /bin/bash
```

Seems like it should be written as:

```
docker run  --privileged -it --name swiftfun swift:latest
```

Removing /bin/bash and adding `--privileged`.

(It wasn't clear to me if the page can be updated via changes to the repo.)

**Comment by tianon** [comment]
See also https://github.com/swiftdocker/docker-swift/issues/9#issuecomment-310072262.

**Comment by swizzlr** [comment]
Action item here is me updating the README.

**Comment by CrowdHailer** [comment]
Hi,

Can if this issue is understood can the docs be updated? I have wasted a bunch of time with the following
```
$ docker run --cap-add sys_ptrace -it --rm swift swift
error: failed to launch REPL process: process launch failed: 'A' packet returned an error: 8
```

**Comment by swizzlr** [comment]
Yeah, we need to add the other capabilities required, as documented by Tianon.

**Comment by shahmishal** [comment]
@rayfix We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
