### ISSUE TITLE
Accelerate Framework and how to use it

### ISSUE THREAD

**Issue by FuzzOli87** [swiftlang/swift-docker#85]
Hello!

I have an application that uses the Accelerate Framework and I'm wondering if there is a way to use it inside this Docker image? I'm aware that some stuff isn't ported over but information about package management etc isn't easy to find for Swift on Docker.

Thanks!

**Comment by swizzlr** [comment]
@FuzzOli87 Apologies for the delay in getting back to you.

I'm sorry to say that, AFAIK, Accelerate is a closed source library that provides API on top of several open source libraries: https://stackoverflow.com/questions/16432028/what-are-the-open-source-equivalents-of-apples-accelerate-framework-libraries

If I were you, I'd write an API compatible "Hackcelerate" Swift package that reimplements the parts of Accelerate that you need, leveraging BLAS/LAPACK and maybe a few other libs as necessary.

The Swift users mailing list would probably also have some ideas.

If you need any help getting any of these old C libs running under `docker-swift`, let us know!
