### ISSUE TITLE
Document current state of the art in deploying Swift binaries in multiple stages

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#89]
I know a few people who have done this. Will ask.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
