### ISSUE TITLE
Image flavors

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#90]
## What are image flavors?

Image flavors are variants of the image that offer different environments. While the main, `default` flavor is the one that supports 80-90% of use cases, we should be able to offer variants that support other use cases to minimize the amount of customization a user needs.

## What's this issue for?

This issue tracks the effort to expand beyond the current `default` flavor into three new flavors:

- `default` flavor will gain more pre-installed dependencies to make quick hacking faster and easier.
- `slim` flavor that can minimally compile a Swift program and do little else.
- `runtime` flavor that has the bare library support for the Swift standard library and Foundation.

Read on for the rationale.

## Related milestones:
1. [slim-compiler](https://github.com/swiftdocker/docker-swift/milestone/1)
2. [slim-runtime](https://github.com/swiftdocker/docker-swift/milestone/2)

## Why do we need image flavors?

There are two kinds of users of `docker-swift`, in my opinion:

### 1. Power/production users who deploy containerized workloads written in Swift
These users want customizable, small containers. The image is big enough as it is and it's frankly embarrassing how slow it is to deploy a Swift workload vs a Go workload into a container orchestrator. They do not want openssl or vim unless they install it themselves.

To address their needs we should offer:
- support for multi stage builds, providing a minimal image with a compiler and nothing* else.
- either:
    - documentation for complete static linking of all dependencies (including standard library, libxml, libicu, libcurl, and whatever else Foundation needs) OR
    - documentation for building a static-ish executable AND a runtime image that contains the stdlib and Foundation dependencies

### 2. "Make it easy for me" users who really want more of a glorified VM
These users want a shell, the Ubuntu environment, and the common external dependencies used by many of the projects currently around (mainly HTTP servers). The VAST MAJORITY of our user base are Mac-based Swift devs who want to test their code locally under Linux, and in some cases aren't even deploying a containerized app. This is what the default image mostly does already, but we have room to expand it.

**Comment by Khalian** [comment]
Is this multiple Dockerfiles under this repo or multiple github projects under one org ? I would prefer the latter.

**Comment by swizzlr** [comment]
@Khalian Multiple Dockerfiles in this repo since that's how most other distros do it. I know it's maybe a bit less simple but it allows us to do templating, and unify work in one place.

I'll be open to changing that at a later date iff it proves unwieldy, but the nodejs docker image manages it that way, and they've been doing this far longer than we have.

**Comment by dsperling** [comment]
I have created a _workaround_ solution for a `slim` image.  I wanted to share it with others to get feedback.
Here is a minimal Dockerfile for **Hello World**:
```
FROM swift:4.1

RUN echo "print(\"Hello World\")" > swift-min.swift \
  && swiftc swift-min.swift -o swift-min

CMD [ "/swift-min" ]
```
This produces an image of 1.35 GB.  

Using the multi-stage build feature, we can derive our application image from the same `ubuntu:16.04` base image as `swift:4.1`.  The Dockerfile essentially copies most libraries used by a Swift app, but nothing else
```
FROM swift:4.1 AS build

RUN echo "print(\"Hello World\")" > swift-min.swift \
  && swiftc swift-min.swift -o swift-min

# Prepare our minimized image
FROM ubuntu:16.04

# copy our app into the path
COPY --from=build /swift-min /usr/local/bin/
# for swift shared objects
COPY --from=build /usr/lib/swift/ /usr/lib/swift/
# for libcurl, libatomic and other shared objects
COPY --from=build /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
# for libssl and other shared objects
COPY --from=build /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu

CMD [ "swift-min" ]
```
This produces an image of 431MB.  You can further reduce the size by eliminating the libraries in  /lib/x86_64-linux-gnu, however this is required if you compile in SSL support (or many other features).  Removing these libraries reduces the image to 227MB.

I have this working with a Kitura application and it working well.  Thoughts?

There is another more sophisticated strategy discussed in this Medium article, but I have not tested this out yet.
https://medium.com/@jjacobson/a-minimal-swift-docker-image-b93d2bc1ce3c

While this is a temporary hack, I wonder if multi-stage builds could be used for `slim` images.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
