### ISSUE TITLE
"Fatten" the default image

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#91]
The default `docker-swift` flavor should have the batteries included to get most common Swift projects off the ground fast.

To add:

- `openssl`
- `libuuid`
- ?

Related to #90. Supersedes #73.

Please add suggestions as necessary.

**Comment by Khalian** [comment]
Shouldnt this suggestion be a separate project? Any all fattening should be different github repos with the required libs added on top of this image. Or is this some special kind of swift install that comes with openssl packages?

**Comment by swizzlr** [comment]
Re my comment in #90, these will be exposed under separate tags, but will be a part of this project.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
