### ISSUE TITLE
Document templating

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#96]
I.e. explain how this works, which is what I'm currently doing:

```bash
sed -e 's/v\$SWIFT_VERSION/swift-3.1.1-RELEASE/' -e 's/v\$SWIFT_BRANCH/swift-3.1.1-release/' Dockerfile.template > 3.1/Dockerfile
```

**Comment by Khalian** [comment]
Its kind of like doing a global substitution in vim via %s/$SWIFT_PROPERTY/actualvalue/g. But you are using sed (streaming ed). Slightly different syntax and more command line friendly. -e stands for edit, s stands for substitute v\ is for everywhere. You are replacing the properties SWIFT_VERSION and SWIFT_BRANCH with the required values. And you seem to have done this twice (once for 3.1 and once for 4). 

If you want to document it, you wanna put it in the README.

**Comment by swizzlr** [comment]
Yep, that's it – this is just a note that we need to do it at some point.

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
