### ISSUE TITLE
Missing tzdata package

### ISSUE THREAD

**Issue by florianreinhart** [swiftlang/swift-docker#98]
`TimeZone(identifier: "Europe/Paris")` returns `nil` and `TimeZone.knownTimeZoneIdentifiers` returns an empty array.

When I manually installed the tzdata apt package both worked as expected.

I can create a PR to fix this. Just let me know.

**Comment by swizzlr** [comment]
@florianreinhart is this a requirement of Foundation? If so, please do so! Could you also find out if this is documented anywhere? I want to ensure we're following this to the letter.

**Comment by florianreinhart** [comment]
I have not found any documentation about this. However, I looked through the Foundation code:

`TimeZone.knownTimeZoneIdentifiers` just calls through to `NSTimeZone.knownTimeZoneIdentifiers`, which in turn uses Core Foundation's `CFTimeZoneCopyKnownNames()`.

 Core Foundation loads the time zone information from `/usr/share/zoneinfo/zone.tab` on Linux, see:

- https://github.com/apple/swift-corelibs-foundation/blob/79b80a8f965f6267a15254a4b8362c307e7b36b5/CoreFoundation/NumberDate.subproj/CFTimeZone.c#L39
- https://github.com/apple/swift-corelibs-foundation/blob/79b80a8f965f6267a15254a4b8362c307e7b36b5/CoreFoundation/NumberDate.subproj/CFTimeZone.c#L738

Assuming that installing tzdata is the preferred way on Ubuntu to get /usr/share/zoneinfo, I think it should installed by default.

**Comment by florianreinhart** [comment]
I found some documentation:

- https://bugs.swift.org/browse/SR-4921
- https://github.com/apple/swift/blob/master/README.md#linux

I'll create a PR to install tzdata.
