### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by swizzlr** [swiftlang/swift-docker#99]
These are required as an official image, and currently exist out of tree, for example: https://github.com/docker-library/official-images/tree/master/test/tests/swift-hello-world

We should bring this into this repo, and have CI check them.

We should also add a test for the timezone support as evidenced by #98.

**Comment by Khalian** [comment]
There are two ways to solve this problem.

1. Shippable supports on_success ci step. I can technically jam the bash script there. This has the obvious advantage of decoupling the build and the test, thereby making shippable optimize the build better. The obvious drawback is we would have to rewrite this if we wanna move to travis or circle CI tomorrow. 

2. COPY the files and run cmd and check the return type. This contains the test inside the Docker file, making the testing more portable around different CI styles. But build times would marginally increase and the docker file gets a little complex. 

I will leave the decision to you. I can draft an impl once I get a go ahead on which one makes more sense. I am in favor of 2.

**Comment by swizzlr** [comment]
Both good options – the third is to use `bashbrew`, which is what the official docker library uses, and we use when PRing our work. For simplicity's sake, that might make more sense. See https://github.com/docker-library/official-images/tree/master/test for more info

**Comment by shahmishal** [comment]
@swizzlr We are moving Swift Docker issues to [https://bugs.swift.org](https://bugs.swift.org) Component: Docker. Can you please file your issue on bugs.swift.org?

We are planning on closing GitHub swift-docker issues on Dec 20th, 2018 (PST).
